title: Hello, welcome to my page :) # your name (or website title) here
logo: "images/133560246728664445.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/yuan-wang2002/">LinkedIn</a> 
  <br>
  <a href="pdf/Yuan Wang_CV.pdf">Resume</a>  
  <br>
  <a href="https://github.com/Saintwy6">GitHub</a>  
  <br>
  <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Youtube</a> 
  
theme: jekyll-theme-minimal
